# https://taskfile.dev

version: '3'

tasks:

  test:
    cmds:
      - task: unit-test
      - task: integration-test

  unit-test:
    cmds:
      - flutter test

  integration-test:
    cmds:
      - flutter clean
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/gherkin_suite_test.dart
