name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - run: flutter pub get
    - run: flutter test
    - uses: vebr/jest-lcov-reporter@v0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: flutter build apk
