name: CI/CD

on:
  [workflow_dispatch, pull_request, push]

env:
  flutter_channel: dev
  java_version: "12.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
      - name: Add credentials
        run: echo '${{ secrets.API_GW_CREDENTIALS }}' > lib/credentials/api_gateway.dart
      - name: Install pub packages
        run: flutter pub get
      - name: Generate Code with build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze Dart Code
        run: flutter analyze .
      - name: Build Android APK
        run: flutter build apk
      - name: Build web version
        run: flutter build web --release
      - name: Upload built Android APK
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Upload built web version
        uses: actions/upload-artifact@v1
        with:
          name: release-web
          path: build/web

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
      - name: Setup Coverage
        uses: stelynx/dart-full-coverage@v1.0.3
        with:
          package: brick_app
      - name: Add credentials
        run: echo '${{ secrets.API_GW_CREDENTIALS }}' > lib/credentials/api_gateway.dart
      - name: Install pub packages
        run: flutter pub get
      - name: Generate Code with build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Test with coverage
        run: flutter test --coverage
      - name: Upload generated coverage reports
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  integration-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
      - name: Add credentials
        run: echo '${{ secrets.API_GW_CREDENTIALS }}' > lib/credentials/api_gateway.dart
      - name: Install pub packages
        run: flutter pub get
      - name: Generate Code with build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Integration test
        env:
          DOTENV: ${{secrets.DOTENV_IT}}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: |
            echo "$DOTENV" > .env
            flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/gherkin_suite_test.dart

  deploy-webapp:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [ build, test, integration-test]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@master
        with:
          name: release-web
          path: build/web
      - name: Deploy to web version to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: build/web
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
